### PR TITLE
Feature/initial test branch

### PR DESCRIPTION
**Pull request by Ruslan-Dulina**
Initial test branch. I've added webstorm files to git ignor list and removed debugger from code base. Added ability to read files from directory. NOTE: outputDirectory flag works only with inPlace flag.

### CODE REVIEW

**Comment by platinumazure** [comment]
Looks good to me. I'm noticing I failed to update the package version from 0.6.0 to 0.6.1-pre-- I'll need to do that first and then you might need to merge master in your feature branch. Keep an eye out for that and then I'll merge the pull request once all is well. Thanks!

**Comment by platinumazure** [comment]
Sorry for the delay. I decided to release the `debugger;` removal as 0.6.1 independently of everything else (because 0.6.0 is effectively a bad release while that line is in there), and I've revved to 0.6.2-pre for your changes. Please fetch and merge the master branch from here into your pull request branch and push that merge commit to this pull request; then I should be able to merge. If things look good, I can then cut release 0.7.0.

This is my first time managing a GitHub repo with pull requests, so I appreciate your patience. :-)

**Comment by platinumazure** [comment]
Merged-- looks good so far, though I'll want to play with it a bit more before cutting a release.

By the way, when you have multiple independent changes, it's good practice to create separate branches for each change and open a pull request for each one. That gives the repo maintainer (here, me) some flexibility in what order to merge changes, as well as the ability to merge pull requests that are fine on the first attempt while providing feedback on pull requests that need modifications.

An example of where that might have helped is with the `debugger;` issue. If that was its own pull request, I could have merged it and cut v0.6.1 immediately and you wouldn't have needed to merge my changes to the master branch in your pull request.

Not a big deal at all-- it's just a suggestion. Especially after working with TFS for a while, it's easy to forget that git is much more flexible with branch creation :-)

**Comment by Ruslan-Dulina** [comment]
Thanks for advice(I know this but I was afraid that it will be hard for you to merge a lot of branches with your master branch so I've created only one :-))

We can fully fix issue with Tabs(it looks like a bug in "recast" library) by adding regexp

recast.prettyPrint(syntax, { useTabs: true }) I've added in last commit.
New proposal
recast.prettyPrint(syntax, { useTabs: true }).code.replace(/     /g, '\t');

What do you think about this fix?

**Comment by platinumazure** [comment]
No worries, I can handle multiple pull requests. I have to juggle multiple
pull requests on the other side (I.e., as a non-core contributor to
projects like QUnit) and am used to it.

That regex won't work because it will replace ALL spaces on the line with
tabs (even a space in `new Object()`). At very least you would want to
anchor the regular expression with `^`. Once you have something you want me
to look at, open a new pull request and I'll take a look :-)

**Comment by Ruslan-Dulina** [comment]
GitHub text editor replace 4 spaces by one :)
recast.prettyPrint(syntax, { useTabs: true }).code.replace(/4 spaces/g, '\t');
I've tested it on ADC tests and it worked fine. .replace(/4 spaces/g, '\t'); should fix this problem
cobalt dashboard slwb - microsoft visual studio administrator 2015-06-09 16 55 24

**Comment by platinumazure** [comment]
Actually- I thought of one other problem: we can't assume tabs in this
project because other codebases will use spaces. We need to provide an
option to use tabs or to use an indent width of N spaces (which itself
could vary between projects).

I was really hoping recast would be smart enough to figure it out from
surrounding lines, but apparently it needs some guidance...

**Pull request merged**
